<b><h1 style="color: #AAA">Numpy</h1></b>

<h3>NumPy is a Python library used for working with arrays.</h3>

In [7]:
import numpy as np

In [8]:
# check numpy version 
np.__version__

'1.20.3'

<h3>Creating Arrays</h3>

In [9]:
# creating a numpy array
arr = np.array([1, 2, 3, 4, 5]) 
arr

array([1, 2, 3, 4, 5])

In [10]:
# check the type of arr
type(arr)

numpy.ndarray

In [17]:
# can use tuples to create arrays
arr_tuple = np.array((1,35,60))
arr_tuple

3

In [19]:
# Can use a dict but does not behave like list or tuple
arr_dict = np.array({"hello": "world", "foo": "bar"})
arr_dict

array({'hello': 'world', 'foo': 'bar'}, dtype=object)

<h3>Dimensions in arrays</h3>

In [34]:
# 0D
arr = np.array(42)
print(f"0D array: {arr} has {arr.ndim} dimensions\n")  # just a scalar

arr = np.array([1, 2, 3, 4, 5])
print(f"1D array: {arr} has {arr.ndim} dimensions\n")

# An array that has 1-D arrays as its elements is called a 2-D array.
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(f"2D array:\n {arr} \n has {arr.ndim} dimensions\n")

# An array that has 2-D arrays (matrices) as its elements is called 3-D array.
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(f"3D array:\n {arr} \n has a {arr.ndim} dimensions")

0D array: 42 has 0 dimensions

1D array: [1 2 3 4 5] has 1 dimensions

2D array:
 [[1 2 3]
 [4 5 6]] 
 has 2 dimensions

3D array:
 [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]] 
 has a 3 dimensions


In [35]:
## an array of any dimensions can be created 
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [40]:
# iterate though high dimension arrays
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [41]:
# enumerate on high dimension arrays
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x) 

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


<h3>Data Types in NumPy</h3>
 <ul >
    <li style="color:white"><b style="color:darkred">i</b> - integer</li>
    <li style="color:white"><b style="color:darkred">b</b> - boolean</li>
    <li style="color:white"><b style="color:darkred">u</b> - unsigned integer</li>
    <li style="color:white"><b style="color:darkred">f</b> - float</li>
    <li style="color:white"><b style="color:darkred">c</b> - complex float</li>
    <li style="color:white"><b style="color:darkred">m</b> - timedelta</li>
    <li style="color:white"><b style="color:darkred">M</b> - datetime</li>
    <li style="color:white"><b style="color:darkred">O</b> - object</li>
    <li style="color:white"><b style="color:darkred">S</b> - string</li>
    <li style="color:white"><b style="color:darkred">U</b> - unicode string</li>
    <li style="color:white"><b style="color:darkred">V</b> - fixed chunk of memory for other type ( void )</li>
 </ul>
    






In [38]:
# reshaping arrays

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [39]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


<h3>Joining Arrays</h3>

In [45]:
# stack() can be used with axis parameter
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.hstack((arr1, arr2))
arr4 = np.vstack((arr1, arr2))
arr5 = np.dstack((arr1, arr2))

print(f"Horizontal stack \n {arr3} \n")
print(f" Vertical stack \n {arr4} \n")
print(f"Depth (height) stack \n {arr5} \n")

Horizontal stack 
 [1 2 3 4 5 6] 

 Vertical stack 
 [[1 2 3]
 [4 5 6]] 

Depth (height) stack 
 [[[1 4]
  [2 5]
  [3 6]]] 



<h3>Splitting Arrays</h3>

In [53]:
arr = np.array(
    [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]]
)
arr3D = np.array(
    [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]]
)

arr1 = np.hsplit(arr, 3)
arr2 = np.vsplit(arr, 3)
arr3 = np.dsplit(arr3D, 3)  # only works on 3D arrays

print(f"Horizontal split \n {arr1} \n")
print(f"Vertical split \n {arr2}")

Horizontal split 
 [array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])] 

Vertical split 
 [array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [51]:
print(arr3)

[array([[[ 1],
        [ 4]],

       [[ 7],
        [10]],

       [[13],
        [16]]]), array([[[ 2],
        [ 5]],

       [[ 8],
        [11]],

       [[14],
        [17]]]), array([[[ 3],
        [ 6]],

       [[ 9],
        [12]],

       [[15],
        [18]]])]


<h3>Array Search</h3>

In [59]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x) 

# assumes sorted array
np.sort(arr).searchsorted(3) # binary search to find index of where argument goes

(array([3, 5, 6], dtype=int64),)


2

<h3>Array Filtering</h3>

In [60]:
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False] # filter array
newarr = arr[x] # returns only where x is true

print(newarr) 

[41 43]


In [61]:
filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr) 

[False  True False  True]
[42 44]
